-- AlterTable
ALTER TABLE `City` MODIFY `CITY_CODE` INTEGER NULL,
    MODIFY `CITY_DS_CODE` VARCHAR(20) NULL DEFAULT 'default_ds_code',
    MODIFY `CITY_DS_NAME` VARCHAR(20) NULL DEFAULT 'default_ds_name',
    MODIFY `CITY_NAME` VARCHAR(20) NULL,
    MODIFY `CITY_PIN_CODE` CHAR(8) NULL,
    MODIFY `CITY_ST_CODE` VARCHAR(20) NULL DEFAULT 'default_st_code',
    MODIFY `CITY_ST_NAME` VARCHAR(20) NULL DEFAULT 'default_st_name';
