/*
  Warnings:

  - You are about to drop the column `PR_PROFESSION` on the `PEOPLE_REGISTRY` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `PEOPLE_REGISTRY` DROP COLUMN `PR_PROFESSION`,
    ADD COLUMN `PR_PROFESSION_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `PROFESSION` (
    `PROF_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROF_DESC` CHAR(50) NOT NULL,
    `PROF_ACTIVE_YN` CHAR(1) NOT NULL,
    `PROF_CREATED_BY` INTEGER NOT NULL,
    `PROF_CREATED_DT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PROF_UPDATED_BY` INTEGER NULL,
    `PROF_UPDATED_DT` DATETIME(3) NULL,

    PRIMARY KEY (`PROF_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PEOPLE_REGISTRY` ADD CONSTRAINT `PEOPLE_REGISTRY_PR_PROFESSION_ID_fkey` FOREIGN KEY (`PR_PROFESSION_ID`) REFERENCES `PROFESSION`(`PROF_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
