-- CreateTable
CREATE TABLE `CONTACT` (
    `CON_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CON_TYPE` CHAR(10) NOT NULL,
    `CON_NAME` CHAR(50) NOT NULL,
    `CON_MOBILE_NO` VARCHAR(20) NOT NULL,
    `CON_ATTACHMENT` CHAR(250) NULL,
    `CON_MORE_DETAIL` VARCHAR(500) NOT NULL,
    `CON_RATING` INTEGER NULL,
    `CON_ACTIVE_YN` CHAR(1) NOT NULL,
    `CON_CREATED_BY` INTEGER NOT NULL,
    `CON_CREATED_DT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CON_UPDATED_BY` INTEGER NULL,
    `CON_UPDATED_DT` DATETIME(3) NULL,

    PRIMARY KEY (`CON_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
